[package]
name = "symphonia-codec-aac"
version = "0.5.4"
description = "Pure Rust AAC decoder (a part of project Symphonia)."
homepage = "https://github.com/pdeljanov/Symphonia"
repository = "https://github.com/pdeljanov/Symphonia"
authors = ["Philip Deljanov <philip.deljanov@gmail.com>", "Kostya Shishkov <kostya.shiskov@gmail.com>"]
license = "MPL-2.0"
readme = "README.md"
categories = ["multimedia", "multimedia::audio", "multimedia::encoding"]
keywords = ["audio", "codec", "decoder", "aac", "m4a"]
edition = "2018"
rust-version = "1.53"

[dependencies]
log = "0.4"
lazy_static = "1.4.0"
symphonia-core = { version = "0.5.4", path = "../symphonia-core" }