[package]
name = "symphonia-utils-xiph"
version = "0.5.5"
description = "Project Symphonia utilities for Xiph codecs and formats."
homepage = "https://github.com/pdeljanov/Symphonia"
repository = "https://github.com/pdeljanov/Symphonia"
authors = ["Philip Deljanov <philip.deljanov@gmail.com>"]
license = "MPL-2.0"
readme = "README.md"
categories = ["multimedia", "multimedia::audio", "multimedia::encoding"]
keywords = ["audio", "multimedia", "media", "xiph"]
edition = "2018"
rust-version = "1.53"

[dependencies]
symphonia-core = { version = "0.5.5", path = "../symphonia-core" }
symphonia-metadata = { version = "0.5.5", path = "../symphonia-metadata" }