[package]
name = "symphonia-play"
description = "Project Symphonia audio player demo application."
authors = ["Philip Deljanov <philip.deljanov@gmail.com>"]
publish = false
default-run = "symphonia-play"
# Common package metadata located in workspace Cargo.toml.
edition.workspace = true
homepage.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[features]
exp-video-codecs = ["symphonia/exp-video-codecs"]
exp-subtitle-codecs = ["symphonia/exp-subtitle-codecs"]

# Enable experimental features since symphonia-play is a development tool.
default = ["exp-subtitle-codecs", "exp-video-codecs"]

[dependencies]
clap = "3.1.0"
lazy_static = "1.4.0"
log = { version = "0.4", features = ["release_max_level_info"] }
pretty_env_logger = "0.4"
symphonia = { version = "0.6.0", path = "../symphonia", features = ["all", "opt-simd"] }

[target.'cfg(target_os = "linux")'.dependencies]
libpulse-binding = "2.5.0"
libpulse-simple-binding = "2.5.0"

[target.'cfg(not(target_os = "linux"))'.dependencies]
cpal = "0.13.3"
rb = "0.3.2"
rubato = "0.14.1"
smallvec = "1.13.1"
