[package]
name = "symphonia-format-mkv"
version = "0.5.1"
description = "Pure Rust MKV/WebM demuxer (a part of project Symphonia)."
homepage = "https://github.com/pdeljanov/Symphonia"
repository = "https://github.com/pdeljanov/Symphonia"
authors = ["Dariusz Niedoba <dariusz.niedoba@gmail.com>"]
license = "MPL-2.0"
readme = "README.md"
categories = ["multimedia", "multimedia::audio", "multimedia::encoding"]
keywords = ["media", "demuxer", "mkv", "matroska", "webm"]
edition = "2018"
rust-version = "1.53"

[dependencies]
log = "0.4"
lazy_static = "1.4.0"
symphonia-core = { version = "0.5", path = "../symphonia-core" }
symphonia-metadata = { version = "0.5", path = "../symphonia-metadata" }
symphonia-utils-xiph = { version = "0.5", path = "../symphonia-utils-xiph" }