[package]
name = "symphonia-core"
version = "0.5.2"
description = "Project Symphonia shared structs, traits, and features."
homepage = "https://github.com/pdeljanov/Symphonia"
repository = "https://github.com/pdeljanov/Symphonia"
authors = ["Philip Deljanov <philip.deljanov@gmail.com>"]
license = "MPL-2.0"
readme = "README.md"
categories = ["multimedia", "multimedia::audio", "multimedia::encoding"]
keywords = ["audio", "codec", "decoder", "multimedia", "media"]
edition = "2018"
rust-version = "1.53"

[dependencies]
arrayvec = "0.7.1"
bitflags = "1.2.1"
bytemuck = "1.7"
lazy_static = "1.4.0"
log = "0.4"
rustfft = "6.1.0"